export enum EScopes {
  OPENID = "OPENID",
  PHONE = "PHONE",
  READ_PROFILE = "READ_PROFILE",
  READ_OUTSLEEP = "READ_OUTSLEEP",
  READ_CLUB = "READ_CLUB",
  READ_DORMITORY = "READ_DORMITORY",
  WRITE_DORMITORY = "WRITE_DORMITORY",
}